In [5]:
import pandas as pd

vendas_df = pd.read_excel('Vendas.xlsx')
vendas_dez_df = pd.read_excel('Vendas - Dez.xlsx')

#concatenando dois arquivos excel com os mesmos campos
vendas_geral_df = pd.concat([vendas_df,vendas_dez_df])
display(vendas_geral_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

In [6]:
#Adicionar uma coluna

vendas_df['Comissão'] = vendas_df['Valor Final'] * 0.05
display(vendas_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissão
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55
...,...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566,28.30
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158,7.90
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201,10.05
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570,28.50
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036,51.80

In [ ]:
#excluir uma linha ou coluna